// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTool(arg1) {
  return window['go']['main']['App']['AddTool'](arg1);
}

export function DowngradeTool(arg1, arg2) {
  return window['go']['main']['App']['DowngradeTool'](arg1, arg2);
}

export function GetAvailableVersions(arg1) {
  return window['go']['main']['App']['GetAvailableVersions'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetToolExplanation(arg1) {
  return window['go']['main']['App']['GetToolExplanation'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function ParseGithubRepo(arg1) {
  return window['go']['main']['App']['ParseGithubRepo'](arg1);
}

export function RefreshAll() {
  return window['go']['main']['App']['RefreshAll']();
}

export function RefreshTool(arg1) {
  return window['go']['main']['App']['RefreshTool'](arg1);
}

export function RemoveTool(arg1) {
  return window['go']['main']['App']['RemoveTool'](arg1);
}

export function SetDeepSeekModel(arg1) {
  return window['go']['main']['App']['SetDeepSeekModel'](arg1);
}

export function SetDeepSeekToken(arg1) {
  return window['go']['main']['App']['SetDeepSeekToken'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}

export function UninstallTool(arg1) {
  return window['go']['main']['App']['UninstallTool'](arg1);
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}
