// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tool} from '../models';
import {main} from '../models';

export function AddTool(arg1:config.ToolSpec):Promise<void>;

export function DowngradeTool(arg1:string,arg2:string):Promise<tool.InstallResult>;

export function GetAvailableVersions(arg1:string):Promise<Array<string>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetToolExplanation(arg1:string):Promise<main.ToolExplanation>;

export function InstallTool(arg1:string):Promise<tool.InstallResult>;

export function ListTools():Promise<Array<tool.ToolStatus>>;

export function ParseGithubRepo(arg1:string):Promise<Record<string, any>>;

export function RefreshAll():Promise<Array<tool.ToolStatus>>;

export function RefreshTool(arg1:string):Promise<tool.ToolStatus>;

export function RemoveTool(arg1:string):Promise<void>;

export function SetDeepSeekModel(arg1:string):Promise<void>;

export function SetDeepSeekToken(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetToken(arg1:string):Promise<void>;

export function UninstallTool(arg1:string):Promise<void>;

export function UpdateTool(arg1:string):Promise<tool.InstallResult>;
